### ISSUE TITLE
Badges don't show up on android.

### ISSUE THREAD

**Issue by nmaswood98** [gogoout/nativescript-plugin-badge#1]
Right now I am using this plugin on a nativescript project for ios and android. The plugin works successfully on ios however it doesn't work when I test it on an android google pixel emulator. I found out that shortcut badger doesn't work on native android but I installed two launchers that are supported by shortcut badger but it still doesn't work and I am not getting any error messages in the console.

**Comment by gogoout** [comment]
The plugin won't work on android emulators, try it on real devices. Check [here](https://github.com/leolin310148/ShortcutBadger) to find the supported devices.
